PROMPTS = [
    "What is the capital of Norway?",
    "Who was the third German king of Bavaria?",
    "Explain the theory of relativity in simple terms.",
    "What is the speed of light in a vacuum?",
    "Who wrote the novel Moby Dick?",
    "What year did World War II end?",
    "What is the chemical formula for water?",
    "Who painted the Mona Lisa?",
    "What is the largest planet in the solar system?",
    "Who developed the theory of general relativity?",
    "What is the boiling point of water in Celsius?",
    "What is the capital of Japan?",
    "Who was the first person to walk on the moon?",
    "What is the square root of 144?",
    "Who invented the telephone?",
    "What is the longest river in the world?",
    "What is the capital of Australia?",
    "Who wrote Romeo and Juliet?",
    "What is the hardest natural substance on Earth?",
    "What is the smallest country in the world?",
    "Who was the first President of the United States?",
    "What is the currency of Japan?",
    "What is the tallest mountain in the world?",
    "Who discovered penicillin?",
    "What is the atomic number of carbon?",
    "What language is spoken in Brazil?",
    "What is the capital of Canada?",
    "Who invented the light bulb?",
    "What is the distance from Earth to the Sun?",
    "Who composed Beethoven's Fifth Symphony?",
    "What is the capital of Germany?",
    "What is the largest ocean on Earth?",
    "Who was Napoleon Bonaparte?",
    "What is the powerhouse of the cell?",
    "What is the capital of France?",
    "Who wrote 1984?",
    "What is the chemical symbol for gold?",
    "How many continents are there on Earth?",
    "Who was the first woman to win a Nobel Prize?",
    "What is the capital of Brazil?",
    "What is photosynthesis?",
    "Who invented the internet?",
    "What is the largest continent by area?",
    "What is the capital of China?",
    "Who was Julius Caesar?",
    "What is the Pythagorean theorem?",
    "What is the capital of India?",
    "Who wrote the Harry Potter series?",
    "What is the melting point of iron in Celsius?",
    "What is the capital of Russia?",
    "Who discovered gravity?",
    "What is the capital of Italy?",
    "What is the primary gas in Earth's atmosphere?",
    "Who built the Great Wall of China?",
    "What is the capital of Spain?",
    "How many bones are in the adult human body?",
    "Who was Cleopatra?",
    "What is the capital of Egypt?",
    "What is the speed of sound in air at sea level?",
    "Who invented the steam engine?",
    "What is the capital of Mexico?",
    "What is DNA and what does it do?",
    "Who was Albert Einstein?",
    "What is the capital of South Korea?",
    "What is the largest desert in the world?",
    "Who wrote the Iliad?",
    "What is the capital of Argentina?",
    "What is the function of the kidney in the human body?",
    "Who was Isaac Newton?",
    "What is the capital of Nigeria?",
    "What is the cruising speed of a commercial airplane?",
    "Who invented the printing press?",
    "What is the capital of Turkey?",
    "What is the theory of evolution?",
    "Who was Marie Curie?",
    "What is the capital of Saudi Arabia?",
    "What is the chemical symbol for silver?",
    "Who was Genghis Khan?",
    "What is the capital of Indonesia?",
    "What is the function of the heart?",
    "Who was Leonardo da Vinci?",
    "What is the capital of Pakistan?",
    "What is the largest mammal on Earth?",
    "Who wrote Don Quixote?",
    "What is the capital of the Netherlands?",
    "What is the rotational speed of the Earth?",
    "Who was Socrates?",
    "What is the capital of Sweden?",
    "What is the chemical symbol for iron?",
    "Who was Nikola Tesla?",
    "What is the capital of Poland?",
    "What is the largest organ in the human body?",
    "Who invented the airplane?",
    "What is the capital of Ukraine?",
    "What is the Big Bang theory?",
    "Who was Charles Darwin?",
    "What is the capital of Greece?",
    "What is the chemical symbol for sodium?",
    "Who was Aristotle?",
    "What is the capital of Portugal?",
]

assert len(PROMPTS) == 100, f"Expected 100 prompts, got {len(PROMPTS)}"